# docker-compose.build.yml
# This file is used for building images on a remote CI/CD server or the AWS EC2 instance.
# It does NOT use the Chinese mirror.

services:
  web:
    image: crpi-34v4qt829vtet2cy.cn-hangzhou.personal.cr.aliyuncs.com/vss_edge/workbench:v1.4.0-alpha # Define the tag for the built image
    restart: always

  worker:
    image: crpi-34v4qt829vtet2cy.cn-hangzhou.personal.cr.aliyuncs.com/vss_edge/workbench:v1.4.0-alpha # Use the same tag
    restart: always

  worker-media:
    image: crpi-34v4qt829vtet2cy.cn-hangzhou.personal.cr.aliyuncs.com/vss_edge/media:v1.4.0-alpha  #等待推送后获得完整地址