# docker-compose.local.yml
# This file is for the local development environment. It overrides the base configuration to build from local source.

services:
  db:
    ports:
      - "15432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.workbench  # <--- 明确指定
    volumes:
      - .:/app

  redis:
    ports:
      - "16379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.workbench
    volumes:
      - .:/app

  # [重点] Media Worker (使用重量级 Dockerfile)
  worker-media:
    build:
      context: .
      dockerfile: Dockerfile.media    # <--- 关键：开发环境也要构建这个特定的镜像
    volumes:
      - .:/app