# Generated by Django 4.2.23 on 2025-12-26 02:39

import uuid

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media_assets", "0006_alter_asset_asset_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("PROBING", "元数据探测中"),
                            ("PROCESSING", "本地精炼中"),
                            ("SYNCING", "云端同步中"),
                            ("READY", "就绪 (Production Ready)"),
                            ("FAILED", "处理失败"),
                        ],
                        default="PENDING",
                        max_length=50,
                        protected=True,
                        verbose_name="精炼进度状态",
                    ),
                ),
                (
                    "proxy_video",
                    models.FileField(
                        blank=True, null=True, upload_to="refinery/proxy/%Y/%m/", verbose_name="代理视频 (720p)"
                    ),
                ),
                (
                    "hls_playlist",
                    models.FileField(blank=True, null=True, upload_to="refinery/hls/%Y/%m/", verbose_name="HLS 播放列表"),
                ),
                (
                    "waveform_data",
                    models.FileField(
                        blank=True, null=True, upload_to="refinery/waveform/%Y/%m/", verbose_name="波形 JSON"
                    ),
                ),
                ("dialogue_track", models.JSONField(blank=True, default=list, verbose_name="结构化对白数据")),
                ("visual_slices", models.JSONField(blank=True, default=list, verbose_name="视觉切片索引")),
                ("keyframe_map", models.JSONField(blank=True, default=dict, verbose_name="关键帧映射表")),
                ("cloud_proxy_path", models.CharField(blank=True, max_length=1024, null=True)),
                ("cloud_slices_path", models.CharField(blank=True, max_length=1024, null=True)),
                ("cloud_dialogue_path", models.CharField(blank=True, max_length=1024, null=True)),
                ("duration", models.FloatField(default=0.0, verbose_name="物理时长")),
                ("tech_meta", models.JSONField(blank=True, default=dict, verbose_name="FFprobe 元数据")),
                ("error_log", models.TextField(blank=True, default="", verbose_name="错误日志")),
                (
                    "media",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material",
                        to="media_assets.media",
                        verbose_name="源媒体文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "精炼物料",
                "verbose_name_plural": "精炼物料",
                "ordering": ["-created"],
            },
        ),
    ]
