# Generated by Django 4.2.23 on 2025-12-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("refinery", "0003_alter_material_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="pipeline_metrics",
            field=models.JSONField(blank=True, default=dict, verbose_name="管线执行指标"),
        ),
    ]
