# Generated by Django 4.2.23 on 2025-12-29 03:32

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("refinery", "0004_material_pipeline_metrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("PENDING", "待处理"),
                    ("FAILED", "处理失败"),
                    ("PROBING", "元数据探测中"),
                    ("TRANSCODING", "标准化转码中"),
                    ("HLS_FRAGMENTING", "HLS切片中"),
                    ("ANALYZING_TEXT", "文本清洗中"),
                    ("SLICING", "视觉切片中"),
                    ("FRAME_EXTRACTING", "提取关键帧中"),
                    ("SYNCING", "云端同步中"),
                    ("CHARACTER_RECOGNIZING", "角色识别中"),
                    ("READY", "就绪 (Production Ready)"),
                    ("PROCESSING", "其他加工中"),
                ],
                default="PENDING",
                max_length=50,
                protected=True,
                verbose_name="精炼进度状态",
            ),
        ),
    ]
