# Generated by Django 4.2.23 on 2025-07-23 21:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='媒资标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('media_type', models.CharField(choices=[('short_drama', '短剧'), ('movie', '电影')], default='short_drama', max_length=20, verbose_name='媒资类型')),
                ('label_studio_project_id', models.IntegerField(blank=True, null=True, verbose_name='Label Studio 项目ID')),
                ('final_narrative_asset', models.JSONField(blank=True, null=True, verbose_name='最终叙事蓝图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '媒资（作品）',
                'verbose_name_plural': '媒资（作品）',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='条目标题')),
                ('sequence_number', models.PositiveIntegerField(default=1, verbose_name='序号')),
                ('language', models.CharField(blank=True, max_length=10, null=True, verbose_name='语言')),
                ('copyright_status', models.CharField(choices=[('pending', '待定'), ('cleared', '已授权'), ('owned', '自有版权'), ('restricted', '受限')], default='pending', max_length=20, verbose_name='版权状态')),
                ('source_video', models.FileField(blank=True, null=True, upload_to='source_files/', verbose_name='源视频文件')),
                ('source_subtitle', models.FileField(blank=True, null=True, upload_to='source_files/', verbose_name='源字幕文件 (SRT)')),
                ('processing_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='物理文件处理状态')),
                ('processing_status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='物理状态变更时间')),
                ('l1_status', models.CharField(choices=[('pending', '未开始'), ('in_progress', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='第一层标注状态')),
                ('l1_status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='L1状态变更时间')),
                ('l2_l3_status', models.CharField(choices=[('pending', '未开始'), ('in_progress', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='第二/三层标注状态')),
                ('l2_l3_status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='L2/L3状态变更时间')),
                ('label_studio_task_id', models.IntegerField(blank=True, null=True, verbose_name='Label Studio 任务ID')),
                ('processed_video_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='处理后视频URL (CDN)')),
                ('l1_output_file', models.FileField(blank=True, null=True, upload_to='l1_outputs/', verbose_name='第一层产出 (.ass)')),
                ('l2_l3_output_file', models.FileField(blank=True, null=True, upload_to='l2_l3_outputs/', verbose_name='第二/三层产出 (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='media_assets.media', verbose_name='所属媒资')),
            ],
            options={
                'verbose_name': '资产条目（剧集）',
                'verbose_name_plural': '资产条目（剧集）',
                'ordering': ['media', 'sequence_number'],
            },
        ),
    ]
