# Generated by Django 4.2.23 on 2025-07-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='source_subtitle_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='源字幕文件URL (CDN/Public)'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='l1_status',
            field=models.CharField(choices=[('pending', '未开始'), ('in_progress', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='第一层标注状态-字幕'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='l2_l3_status',
            field=models.CharField(choices=[('pending', '未开始'), ('in_progress', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='第二/三层标注状态-打标'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='language',
            field=models.CharField(choices=[('zh-CN', '中文 (简体)'), ('en-US', '英语 (美国)')], default='zh-CN', max_length=10, verbose_name='语言'),
        ),
    ]
