# Generated by Django 4.2.23 on 2025-07-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0002_asset_source_subtitle_url_alter_asset_l1_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='l2_l3_output_file',
        ),
        migrations.RemoveField(
            model_name='media',
            name='final_narrative_asset',
        ),
        migrations.AddField(
            model_name='media',
            name='blueprint_status',
            field=models.CharField(default='pending', max_length=20, verbose_name='叙事蓝图生成状态'),
        ),
        migrations.AddField(
            model_name='media',
            name='label_studio_export_file',
            field=models.FileField(blank=True, null=True, upload_to='ls_exports/', verbose_name='Label Studio 导出文件'),
        ),
    ]
