# Generated by Django 4.2.23 on 2025-07-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0003_remove_asset_l2_l3_output_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='ingestion_status',
            field=models.CharField(choices=[('pending', '等待文件上传'), ('ingesting', '加载处理中'), ('completed', '加载完成'), ('failed', '加载失败')], default='pending', max_length=20, verbose_name='批量加载状态'),
        ),
    ]
