# Generated by Django 4.2.23 on 2025-12-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_assets", "0004_media_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="content_genre",
            field=models.CharField(
                choices=[
                    ("drama", "Drama"),
                    ("comedy", "Comedy"),
                    ("action", "Action"),
                    ("thriller", "Thriller"),
                    ("sci_fi", "Sci-Fi"),
                    ("romance", "Romance"),
                    ("horror", "Horror"),
                    ("documentary", "Documentary"),
                    ("animation", "Animation"),
                    ("fantasy", "Fantasy"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
                verbose_name="Genre",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="known_characters",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of character names known in this asset.",
                verbose_name="Known Characters",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("movie", "Movie"),
                    ("series", "Series"),
                    ("series_episode", "Series Episode"),
                    ("short_video", "Short Video"),
                    ("documentary", "Documentary"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
                verbose_name="Asset Type",
            ),
        ),
    ]
