# Generated by Django 4.2.23 on 2025-08-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0004_media_ingestion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='final_blueprint_file',
            field=models.FileField(blank=True, null=True, upload_to='blueprints/', verbose_name='最终叙事蓝图 (JSON)'),
        ),
    ]