# Generated by Django 4.2.23 on 2025-08-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0005_media_final_blueprint_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='ingestion_status',
            new_name='upload_status',
        ),
        migrations.AddField(
            model_name='media',
            name='processing_status',
            field=models.CharField(choices=[('pending', '等待处理'), ('processing', '处理中'), ('completed', '全部处理完成'), ('failed', '部分或全部失败')], default='pending', max_length=20, verbose_name='文件处理状态'),
        ),
        migrations.AlterField(
            model_name='media',
            name='upload_status',
            field=models.CharField(choices=[('pending', '等待文件上传'), ('uploading', '上传中'), ('completed', '上传完成'), ('failed', '上传失败')], default='pending', max_length=20, verbose_name='批量上传状态'),
        ),
    ]