# Generated by Django 4.2.23 on 2025-12-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_assets", "0005_asset_content_genre_asset_known_characters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("feature_film", "电影 (Feature Film)"),
                    ("series_episode", "剧集 (Series Episode)"),
                    ("short_clip", "短片 (Short Clip)"),
                    ("documentary", "纪录片 (Documentary)"),
                    ("raw_footage", "素材 (Raw Footage)"),
                    ("other", "其他 (Other)"),
                ],
                default="other",
                max_length=50,
                verbose_name="Asset Type",
            ),
        ),
    ]
