# Generated by Django 4.2.23 on 2025-08-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0006_rework_media_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='copyright_status',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='language',
        ),
        migrations.AddField(
            model_name='media',
            name='copyright_status',
            field=models.CharField(choices=[('pending', '待定'), ('cleared', '已授权'), ('owned', '自有版权'), ('restricted', '受限')], default='pending', max_length=20, verbose_name='版权状态'),
        ),
        migrations.AddField(
            model_name='media',
            name='language',
            field=models.CharField(choices=[('zh-CN', '中文 (简体)'), ('en-US', '英语 (美国)')], default='zh-CN', max_length=10, verbose_name='语言'),
        ),
    ]