# Generated by Django 4.2.23 on 2026-01-06 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media_assets", "0006_alter_asset_asset_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="waveform_data",
        ),
    ]
