# Generated by Django 4.2.23 on 2025-08-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0007_move_language_copyright_to_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='processing_status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('updated', '已更新'), ('failed', '失败')], default='pending', max_length=20, verbose_name='物理文件处理状态'),
        ),
        migrations.AlterField(
            model_name='media',
            name='upload_status',
            field=models.CharField(choices=[('pending', '等待文件上传'), ('uploading', '上传中'), ('completed', '上传完成'), ('failed', '上传失败')], default='pending', max_length=20, verbose_name='文件上传状态'),
        ),
    ]
