# Generated by Django 4.2.23 on 2026-01-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_assets", "0007_remove_media_waveform_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="orientation",
            field=models.CharField(
                choices=[("landscape", "横屏 (Landscape)"), ("portrait", "竖屏 (Portrait)"), ("unknown", "未知 (Unknown)")],
                default="unknown",
                max_length=20,
                verbose_name="画幅方向",
            ),
        ),
    ]
