# Generated by Django 4.2.23 on 2025-08-13
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0007_move_language_copyright_to_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='character_audit_report',
            field=models.FileField(blank=True, null=True, upload_to='audit_reports/l1_character/', verbose_name='角色名审计报告 (CSV)'),
        ),
    ]