# Generated by Django 4.2.23 on 2025-08-14 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0008_alter_asset_processing_status_and_more'),
        ('media_assets', '0009_media_character_audit_report'),
    ]

    operations = [
    ]
