# Generated by Django 4.2.23 on 2025-08-13
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        # 确保这里的依赖指向您上一个迁移文件，例如 '0010_merge_...'
        ('media_assets', '0010_merge_20250814_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='l2_validation_report',
            field=models.JSONField(blank=True, null=True, verbose_name='L2/L3 标注验证报告'),
        ),
    ]