# Generated by Django 4.2.23 on 2025-08-14
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        # 确保这里的依赖指向您上一个迁移文件
        ('media_assets', '0011_media_l2_validation_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='l2_validation_report',
            new_name='blueprint_validation_report',
        ),
    ]