# Generated by Django 4.2.23 on 2026-01-20 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0007_remove_integrationsettings_label_studio_access_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integrationsettings",
            name="aws_access_key_id",
        ),
        migrations.RemoveField(
            model_name="integrationsettings",
            name="aws_s3_custom_domain",
        ),
        migrations.RemoveField(
            model_name="integrationsettings",
            name="aws_s3_region_name",
        ),
        migrations.RemoveField(
            model_name="integrationsettings",
            name="aws_secret_access_key",
        ),
        migrations.RemoveField(
            model_name="integrationsettings",
            name="aws_storage_bucket_name",
        ),
        migrations.RemoveField(
            model_name="integrationsettings",
            name="storage_backend",
        ),
    ]
