# Generated by Django 4.2.23 on 2026-02-08 21:34

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("atomflow", "0008_material_frames_alter_material_keyframe_map"),
    ]

    operations = [
        migrations.CreateModel(
            name="DubbingAtomRule",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", models.CharField(max_length=50, unique=True)),
                ("mode", models.CharField(default="PROD", max_length=10)),
                ("rules_config", models.JSONField(default=list)),
                ("step_count", models.PositiveIntegerField(default=0, editable=False, verbose_name="步骤数")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Dubbing配音规则",
                "verbose_name_plural": "Dubbing配音规则",
            },
        ),
        migrations.CreateModel(
            name="DubbingAtomUnit",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("execution_mode", models.CharField(choices=[("SYNC", "同步"), ("ASYNC", "异步")], max_length=10)),
                (
                    "resource_class",
                    models.CharField(
                        choices=[
                            ("GENERAL", "通用"),
                            ("NETWORK", "网络"),
                            ("IO", "存储"),
                            ("COMPUTING", "计算"),
                            ("AI", "人工智能"),
                            ("TRANSFER", "传输"),
                        ],
                        max_length=20,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Dubbing配音算子",
                "verbose_name_plural": "Dubbing配音算子",
            },
        ),
        migrations.CreateModel(
            name="DubbingSession",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("stem_vocals", models.CharField(blank=True, max_length=1024, verbose_name="人声分轨路径")),
                ("stem_inst", models.CharField(blank=True, max_length=1024, verbose_name="伴奏分轨路径")),
                ("gating_meta", models.JSONField(blank=True, default=dict, verbose_name="门控元数据")),
                ("track_enhanced", models.CharField(blank=True, max_length=1024, verbose_name="增强人声路径")),
                ("track_material", models.CharField(blank=True, max_length=1024, verbose_name="背景素材轨路径")),
                ("track_perception", models.CharField(blank=True, max_length=1024, verbose_name="感知单声道路径")),
                ("perception_meta", models.JSONField(blank=True, default=dict, verbose_name="感知分析结果")),
                ("debug_paths", models.JSONField(blank=True, default=dict, verbose_name="调试文件路径表")),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dubbing_sessions",
                        to="atomflow.material",
                        verbose_name="源精炼物料",
                    ),
                ),
            ],
            options={
                "verbose_name": "配音会话",
                "verbose_name_plural": "配音会话",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="DubbingAtomPipeline",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待"),
                            ("RUNNING", "运行中"),
                            ("SUCCESS", "已完成"),
                            ("FAILED", "失败"),
                            ("STOPPED", "已停止"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("metrics", models.JSONField(default=dict, help_text="记录格式: {seq: {status, duration, at, error}}")),
                ("stop_point", models.IntegerField(blank=True, help_text="最后停下的 seq 编号", null=True)),
                ("error_log", models.TextField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("target_id", models.CharField(db_index=True, max_length=64, verbose_name="关联SessionID")),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dubbing.dubbingatomrule", verbose_name="使用规则"
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline",
                        to="dubbing.dubbingsession",
                        verbose_name="关联配音会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dubbing配音轨迹",
                "verbose_name_plural": "Dubbing配音轨迹",
            },
        ),
    ]
