# Generated by Django 4.2.23 on 2026-02-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dubbing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dubbingatompipeline",
            name="target_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name="关联SessionID"),
        ),
    ]
