# Generated by Django 4.2.23 on 2026-02-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dubbing", "0002_alter_dubbingatompipeline_target_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="dubbingsession",
            name="ocr_csv_path",
            field=models.CharField(blank=True, max_length=1024, verbose_name="OCR索引路径"),
        ),
        migrations.AddField(
            model_name="dubbingsession",
            name="video_clean",
            field=models.CharField(blank=True, max_length=1024, verbose_name="去字幕视频路径"),
        ),
    ]
