# Generated by Django 4.2.23 on 2026-02-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dubbing", "0003_dubbingsession_ocr_csv_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dubbingsession",
            name="face_csv_path",
            field=models.CharField(blank=True, max_length=1024, verbose_name="人脸索引路径"),
        ),
        migrations.AddField(
            model_name="dubbingsession",
            name="fused_metadata",
            field=models.JSONField(blank=True, default=list, verbose_name="视听融合结果"),
        ),
    ]
