# Generated by Django 4.2.23 on 2026-02-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dubbing", "0004_dubbingsession_face_csv_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dubbingsession",
            name="mask_gating_path",
            field=models.CharField(blank=True, max_length=1024, verbose_name="门控掩码路径"),
        ),
    ]
