# Generated by Django 4.2.23 on 2026-02-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dubbing", "0005_dubbingsession_mask_gating_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="dubbingsession",
            name="refined_script",
            field=models.JSONField(blank=True, default=dict, verbose_name="AI精修脚本"),
        ),
    ]
