#!/bin/bash
# 文件路径: D:/DevProjects/PyCharmProjects/visify-ssw/init_setup.sh
# 描述: 交互式配置生成器。读取 .env.template -> 生成 .env

set -e

# [关键] 切换到项目根目录 (因为脚本现在位于 scripts/ 子目录)
#cd "$(dirname "$0")/.." || exit 1

ENV_TEMPLATE_FILE=".env.template"
ENV_FILE=".env"
REQUIRED_DIRS=("media_root" "staticfiles" "configs/nginx")

# --- Helper Functions ---
generate_secret() {
    openssl rand -hex 32
}

check_file_exists() {
    if [ ! -f "$1" ]; then
        echo "❌ 错误: 关键文件 '$1' 未找到。"
        exit 1
    fi
}

echo "================================================"
echo "⚙️  VSS Edge - 配置初始化"
echo "================================================"

check_file_exists "$ENV_TEMPLATE_FILE"

# 1. 处理 .env 文件覆盖逻辑
if [ -f "$ENV_FILE" ]; then
    read -p "⚠️  '$ENV_FILE' 已存在。是否覆盖并重新配置? [y/N]: " confirm
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
        echo "已取消配置。"
        exit 0
    fi
fi

echo "📄 基于模板生成配置文件..."
cp "$ENV_TEMPLATE_FILE" "$ENV_FILE"

# 2. 生成安全密钥
echo "🔐 生成安全密钥..."
DJANGO_SECRET_KEY=$(generate_secret)
POSTGRES_PASSWORD=$(generate_secret)

# 使用 sed 替换 (兼容 Linux/macOS)
sed -i.bak "s|DJANGO_SECRET_KEY=.*|DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}|" "$ENV_FILE"
sed -i.bak "s|POSTGRES_PASSWORD=.*|POSTGRES_PASSWORD=${POSTGRES_PASSWORD}|" "$ENV_FILE"

# 3. 交互式配置
echo "------------------------------------------------"
echo "请配置实例基本信息:"

# --- Public Endpoint ---
read -p "请输入服务器公网/局域网访问地址 (例如 http://192.168.1.100): " PUBLIC_ENDPOINT
PUBLIC_ENDPOINT=${PUBLIC_ENDPOINT%/} # 去除末尾斜杠

# 智能推导
URL_SCHEME=$(echo "$PUBLIC_ENDPOINT" | grep -oE "^https?") || URL_SCHEME="http"
CURRENT_HOST=$(echo "$PUBLIC_ENDPOINT" | sed -E 's|https?://||' | sed -E 's|:[0-9]+.*||' | sed 's|/.*||')
PORT_MEDIA=9999
LOCAL_MEDIA_URL_BASE="${URL_SCHEME}://${CURRENT_HOST}:${PORT_MEDIA}"

echo "   -> 自动推导 Local Media URL: ${LOCAL_MEDIA_URL_BASE}"

# 写入 Endpoint 配置
if grep -q "PUBLIC_ENDPOINT=" "$ENV_FILE"; then
    sed -i.bak "s|PUBLIC_ENDPOINT=.*|PUBLIC_ENDPOINT=${PUBLIC_ENDPOINT}|" "$ENV_FILE"
else
    echo "PUBLIC_ENDPOINT=${PUBLIC_ENDPOINT}" >> "$ENV_FILE"
fi

sed -i.bak '/^LOCAL_MEDIA_URL_BASE=/d' "$ENV_FILE"
echo "LOCAL_MEDIA_URL_BASE=${LOCAL_MEDIA_URL_BASE}" >> "$ENV_FILE"

# --- Superuser ---
echo
read -p "请输入初始管理员邮箱 (Email): " DJANGO_SUPERUSER_EMAIL
read -s -p "请输入初始管理员密码: " DJANGO_SUPERUSER_PASSWORD
echo

# --- Cloud API ---
echo
echo "--- Cloud API Configuration (VSS-Cloud) ---"
read -p "Cloud API Base URL (e.g., http://cloud.example.com): " CLOUD_API_BASE_URL
read -p "Cloud Instance ID (Edge ID): " CLOUD_INSTANCE_ID
read -p "Cloud API Key: " CLOUD_API_KEY
echo

# --- Allowed Hosts ---
DEFAULT_ALLOWED_HOSTS="localhost,127.0.0.1,${CURRENT_HOST}"
read -p "允许访问的主机名 (逗号分隔) [默认: ${DEFAULT_ALLOWED_HOSTS}]: " DJANGO_ALLOWED_HOSTS
DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-$DEFAULT_ALLOWED_HOSTS}

# 4. 写入剩余配置
sed -i.bak "s|DJANGO_SUPERUSER_EMAIL=.*|DJANGO_SUPERUSER_EMAIL=\"${DJANGO_SUPERUSER_EMAIL}\"|" "$ENV_FILE"
sed -i.bak "s|DJANGO_SUPERUSER_PASSWORD=.*|DJANGO_SUPERUSER_PASSWORD=\"${DJANGO_SUPERUSER_PASSWORD}\"|" "$ENV_FILE"
sed -i.bak "s|DJANGO_ALLOWED_HOSTS=.*|DJANGO_ALLOWED_HOSTS=\"${DJANGO_ALLOWED_HOSTS}\"|" "$ENV_FILE"

# [关键] 将 Cloud 配置追加到 .env 供 init_exec.sh 使用
# 这些变量以 SETUP_ 开头，避免与 Django 内部配置混淆，但在执行脚本中会被读取
echo "" >> "$ENV_FILE"
echo "# --- Setup Variables (Generated by init_setup.sh for init_exec.sh) ---" >> "$ENV_FILE"
echo "SETUP_CLOUD_API_BASE_URL=\"${CLOUD_API_BASE_URL}\"" >> "$ENV_FILE"
echo "SETUP_CLOUD_INSTANCE_ID=\"${CLOUD_INSTANCE_ID}\"" >> "$ENV_FILE"
echo "SETUP_CLOUD_API_KEY=\"${CLOUD_API_KEY}\"" >> "$ENV_FILE"

# 清理备份
rm -f "${ENV_FILE}.bak"
chmod 600 "$ENV_FILE"

# 5. 创建目录
echo "📂 创建必要目录..."
for dir in "${REQUIRED_DIRS[@]}"; do
    mkdir -p "$dir"
    chmod -R 777 "$dir"
done

echo "✅ 配置生成成功！文件已保存为: $ENV_FILE"
echo "👉 下一步：请运行 ./init_exec.sh 执行部署。"