# Generated by Django 4.2.23 on 2026-01-15 08:30

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VectorIndex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("target_id", models.CharField(db_index=True, max_length=64, verbose_name="关联目标ID")),
                ("index_type", models.CharField(max_length=32, verbose_name="索引类型")),
                ("file_path", models.CharField(max_length=1024, verbose_name="索引文件路径")),
                ("vector_count", models.IntegerField(default=0, verbose_name="向量数量")),
                ("dimension", models.IntegerField(default=0, verbose_name="向量维度")),
                ("model_name", models.CharField(max_length=128, verbose_name="Embedding模型")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "向量索引资产",
                "verbose_name_plural": "向量索引资产",
                "indexes": [models.Index(fields=["target_id", "index_type"], name="vector_vect_target__7356af_idx")],
            },
        ),
    ]
