# Generated by Django 4.2.23 on 2026-01-18 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0001_initial"),
        ("vector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorSourceJob",
            fields=[],
            options={
                "verbose_name": "待索引标注任务",
                "verbose_name_plural": "待索引标注任务",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("workflow.annotationjob",),
        ),
    ]
