# Generated by Django 4.2.23 on 2026-01-18 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media_assets", "0008_asset_orientation"),
        ("vector", "0002_vectorsourcejob"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorSourceAsset",
            fields=[],
            options={
                "verbose_name": "待索引资产 (Asset)",
                "verbose_name_plural": "待索引资产 (Asset)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("media_assets.asset",),
        ),
    ]
