# Generated by Django 4.2.23 on 2026-01-20 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vector", "0003_vectorsourceasset"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VectorSourceJob",
        ),
    ]
