# Generated by Django 4.2.23 on 2025-12-31 08:01

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media_assets", "0006_alter_asset_asset_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("proxy_video", models.CharField(blank=True, max_length=1024, verbose_name="代理视频 (720p)地址")),
                ("hls_playlist", models.CharField(blank=True, max_length=1024, verbose_name="HLS 播放列表索引文件地址")),
                ("waveform_data", models.JSONField(blank=True, default=list, verbose_name="波形JSON")),
                ("dialogue_track", models.JSONField(blank=True, default=list, verbose_name="结构化对白数据")),
                ("visual_slices", models.JSONField(blank=True, default=list, verbose_name="视觉切片索引")),
                ("keyframe_map", models.JSONField(blank=True, default=dict, verbose_name="关键帧映射表")),
                ("cloud_proxy_path", models.CharField(blank=True, max_length=1024, null=True)),
                ("cloud_slices_path", models.CharField(blank=True, max_length=1024, null=True)),
                ("cloud_dialogue_path", models.CharField(blank=True, max_length=1024, null=True)),
                ("duration", models.FloatField(default=0.0, verbose_name="物理时长")),
                ("tech_meta", models.JSONField(blank=True, default=dict, verbose_name="FFprobe 元数据")),
                ("error_log", models.TextField(blank=True, default="", verbose_name="错误日志")),
                (
                    "media",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material",
                        to="media_assets.media",
                        verbose_name="源媒体文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "精炼物料",
                "verbose_name_plural": "精炼物料",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="RefineryAtomRule",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", models.CharField(max_length=50, unique=True)),
                ("mode", models.CharField(default="PROD", max_length=10)),
                ("rules_config", models.JSONField(default=list)),
                ("step_count", models.PositiveIntegerField(default=0, editable=False, verbose_name="步骤数")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Atomflow精炼规则",
                "verbose_name_plural": "Atomflow精炼规则",
            },
        ),
        migrations.CreateModel(
            name="RefineryAtomUnit",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("execution_mode", models.CharField(choices=[("SYNC", "同步"), ("ASYNC", "异步")], max_length=10)),
                (
                    "resource_class",
                    models.CharField(
                        choices=[
                            ("GENERAL", "通用"),
                            ("NETWORK", "网络"),
                            ("IO", "存储"),
                            ("COMPUTING", "计算"),
                            ("AI", "人工智能"),
                            ("TRANSFER", "传输"),
                        ],
                        max_length=20,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Atomflow精炼算子",
                "verbose_name_plural": "Atomflow精炼算子",
            },
        ),
        migrations.CreateModel(
            name="RefineryAtomPipeline",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待"),
                            ("RUNNING", "运行中"),
                            ("SUCCESS", "已完成"),
                            ("FAILED", "失败"),
                            ("STOPPED", "已停止"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("metrics", models.JSONField(default=dict, help_text="记录格式: {seq: {status, duration, at, error}}")),
                ("stop_point", models.IntegerField(blank=True, help_text="最后停下的 seq 编号", null=True)),
                ("error_log", models.TextField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("target_id", models.CharField(db_index=True, max_length=64, verbose_name="关联物料ID")),
                (
                    "material",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline",
                        to="atomflow.material",
                        verbose_name="关联物料",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="atomflow.refineryatomrule", verbose_name="使用规则"
                    ),
                ),
            ],
            options={
                "verbose_name": "Atomflow精炼轨迹",
                "verbose_name_plural": "Atomflow精炼轨迹",
            },
        ),
    ]
