# Generated by Django 4.2.23 on 2026-01-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atomflow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="visual_slices",
        ),
        migrations.AddField(
            model_name="material",
            name="slices",
            field=models.JSONField(blank=True, default=list, verbose_name="多模态切片索引"),
        ),
    ]
