# Generated by Django 4.2.23 on 2026-01-05 01:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("atomflow", "0002_remove_material_visual_slices_material_slices"),
    ]

    operations = [
        migrations.RenameField(
            model_name="material",
            old_name="dialogue_track",
            new_name="dialogue",
        ),
    ]
