# Generated by Django 4.2.23 on 2026-01-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atomflow", "0003_rename_dialogue_track_material_dialogue"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="scenes",
            field=models.JSONField(blank=True, default=list, verbose_name="场景列表"),
        ),
    ]
