# Generated by Django 4.2.23 on 2026-01-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atomflow", "0004_material_scenes"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="local_vector_index_path",
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name="本地向量索引路径"),
        ),
    ]
