# Generated by Django 4.2.23 on 2026-01-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atomflow", "0005_material_local_vector_index_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="cloud_dialogue_path",
        ),
        migrations.RemoveField(
            model_name="material",
            name="cloud_proxy_path",
        ),
        migrations.RemoveField(
            model_name="material",
            name="cloud_slices_path",
        ),
        migrations.RemoveField(
            model_name="material",
            name="dialogue",
        ),
        migrations.RemoveField(
            model_name="material",
            name="error_log",
        ),
        migrations.RemoveField(
            model_name="material",
            name="local_vector_index_path",
        ),
        migrations.AddField(
            model_name="material",
            name="dialogues",
            field=models.JSONField(blank=True, default=list, verbose_name="对白容器"),
        ),
        migrations.AddField(
            model_name="material",
            name="scene_vector_index_path",
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name="场景向量索引路径"),
        ),
        migrations.AddField(
            model_name="material",
            name="slice_vector_index_path",
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name="切片向量索引路径"),
        ),
        migrations.AlterField(
            model_name="material",
            name="scenes",
            field=models.JSONField(blank=True, default=list, verbose_name="场景容器"),
        ),
        migrations.AlterField(
            model_name="material",
            name="slices",
            field=models.JSONField(blank=True, default=list, verbose_name="多模态切片容器"),
        ),
    ]
