# Generated by Django 4.2.23 on 2026-01-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atomflow", "0006_remove_material_cloud_dialogue_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="identified_characters",
            field=models.JSONField(blank=True, default=list, verbose_name="识别角色清单"),
        ),
    ]
