# Generated by Django 4.2.23 on 2026-01-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atomflow", "0007_material_identified_characters"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="frames",
            field=models.JSONField(blank=True, default=list, verbose_name="扁平化关键帧列表"),
        ),
        migrations.AlterField(
            model_name="material",
            name="keyframe_map",
            field=models.JSONField(blank=True, default=dict, verbose_name="关键帧映射表(Legacy)"),
        ),
    ]
