# Generated by Django 4.2.23 on 2026-01-18 12:47

import uuid

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models

import apps.workflow.annotation.projects


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media_assets", "0008_asset_orientation"),
        ("configuration", "0007_remove_integrationsettings_label_studio_access_token"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("QUEUED", "排队中"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("REVISING", "修订中"),
                            ("ERROR", "错误"),
                            ("QA_PENDING", "待审核"),
                        ],
                        default="PENDING",
                        max_length=50,
                        protected=True,
                        verbose_name="任务状态",
                    ),
                ),
                ("source_object_id", models.PositiveIntegerField()),
                ("delivery_url", models.URLField(blank=True, max_length=1024, null=True, verbose_name="分发后URL (CDN)")),
                (
                    "source_content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "verbose_name": "分发任务",
                "verbose_name_plural": "分发任务",
            },
        ),
        migrations.CreateModel(
            name="CreativeProject",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="项目描述")),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("default", "标准创作 (Director)"),
                            ("template", "母本模板 (Template)"),
                            ("batch", "批量衍生 (Batch)"),
                        ],
                        default="default",
                        max_length=20,
                        verbose_name="项目类型",
                    ),
                ),
                (
                    "narration_script_file",
                    models.FileField(
                        blank=True, null=True, upload_to="creative/narration/", verbose_name="解说词脚本 (JSON)"
                    ),
                ),
                (
                    "localized_script_file",
                    models.FileField(
                        blank=True, null=True, upload_to="creative/localized/", verbose_name="本地化脚本 (JSON)"
                    ),
                ),
                (
                    "dubbing_script_file",
                    models.FileField(blank=True, null=True, upload_to="creative/dubbing/", verbose_name="配音脚本 (JSON)"),
                ),
                (
                    "edit_script_file",
                    models.FileField(blank=True, null=True, upload_to="creative/edit/", verbose_name="剪辑脚本 (JSON)"),
                ),
                (
                    "final_video_file",
                    models.FileField(blank=True, null=True, upload_to="creative/output/", verbose_name="最终成片"),
                ),
                ("auto_config", models.JSONField(blank=True, default=dict, verbose_name="参数配置快照")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("NARRATION_RUNNING", "Generating Narration"),
                            ("NARRATION_COMPLETED", "Narration Ready"),
                            ("LOCALIZATION_RUNNING", "Localizing"),
                            ("LOCALIZATION_COMPLETED", "Localized"),
                            ("AUDIO_RUNNING", "Generating Audio"),
                            ("AUDIO_COMPLETED", "Audio Ready"),
                            ("EDIT_RUNNING", "Generating EditingScript"),
                            ("EDIT_COMPLETED", "EditingScript Ready"),
                            ("SYNTHESIS_RUNNING", "Synthesizing"),
                            ("COMPLETED", "All Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="CREATED",
                        max_length=50,
                        verbose_name="当前状态",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_projects",
                        to="media_assets.asset",
                        verbose_name="关联资产",
                    ),
                ),
            ],
            options={
                "verbose_name": "创作项目 (Creative Project)",
                "verbose_name_plural": "创作项目 (Creative Projects)",
                "ordering": ["-modified"],
            },
        ),
        migrations.CreateModel(
            name="CreativeJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("QUEUED", "排队中"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("REVISING", "修订中"),
                            ("ERROR", "错误"),
                            ("QA_PENDING", "待审核"),
                        ],
                        default="PENDING",
                        max_length=50,
                        protected=True,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("GENERATE_NARRATION", "生成解说词"),
                            ("LOCALIZE_NARRATION", "本地化/翻译"),
                            ("GENERATE_AUDIO", "生成配音"),
                            ("GENERATE_EDIT_SCRIPT", "生成剪辑脚本"),
                            ("SYNTHESIS", "视频合成"),
                        ],
                        max_length=30,
                        verbose_name="任务类型",
                    ),
                ),
                ("input_params", models.JSONField(blank=True, null=True, verbose_name="输入参数")),
                ("cloud_task_id", models.CharField(blank=True, max_length=255, null=True, verbose_name="云端任务 ID")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="workflow.creativeproject",
                        verbose_name="所属创作项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "子任务状态列表",
                "verbose_name_plural": "子任务状态列表",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationProject",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="项目描述")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "待处理"), ("PROCESSING", "处理中"), ("COMPLETED", "已完成"), ("FAILED", "失败")],
                        default="PENDING",
                        max_length=30,
                        verbose_name="项目状态",
                    ),
                ),
                (
                    "annotation_audit_report",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.annotation.projects.get_audit_upload_path,
                        verbose_name="标注审计报告 (Current)",
                    ),
                ),
                (
                    "annotation_audit_report_backup",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.annotation.projects.get_audit_upload_path,
                        verbose_name="标注审计报告 (Backup)",
                    ),
                ),
                (
                    "project_export_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.annotation.projects.get_project_export_path,
                        verbose_name="工程全量导出 (Current)",
                    ),
                ),
                (
                    "project_export_file_backup",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.annotation.projects.get_project_export_path,
                        verbose_name="工程全量导出 (Backup)",
                    ),
                ),
                (
                    "final_blueprint_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.annotation.projects.get_blueprint_upload_path,
                        verbose_name="生产消费蓝图 (Current)",
                    ),
                ),
                (
                    "final_blueprint_file_backup",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workflow.annotation.projects.get_blueprint_upload_path,
                        verbose_name="生产消费蓝图 (Backup)",
                    ),
                ),
                (
                    "orchestration_graph",
                    models.JSONField(
                        blank=True,
                        help_text="存储用户在编排工作台保存的逻辑结构数据。",
                        null=True,
                        verbose_name="编排图谱 (Orchestration Graph)",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_projects",
                        to="media_assets.asset",
                        verbose_name="关联资产",
                    ),
                ),
                (
                    "source_encoding_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="选择一个编码配置。标注工具将使用此配置转码后的视频，以加快加载速度。",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="configuration.encodingprofile",
                        verbose_name="源编码配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "标注项目",
                "verbose_name_plural": "标注项目",
            },
        ),
        migrations.CreateModel(
            name="AnnotationJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("QUEUED", "排队中"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("REVISING", "修订中"),
                            ("ERROR", "错误"),
                            ("QA_PENDING", "待审核"),
                        ],
                        default="PENDING",
                        max_length=50,
                        protected=True,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, help_text="当前工作区的全量标注数据", verbose_name="标注数据 (Current)"),
                ),
                (
                    "data_backup",
                    models.JSONField(blank=True, default=dict, help_text="上一次保存或修订前的快照", verbose_name="标注数据 (Backup)"),
                ),
                ("dialogues", models.JSONField(blank=True, default=list, verbose_name="对白 (RAG)")),
                ("scenes", models.JSONField(blank=True, default=list, verbose_name="场景 (RAG)")),
                ("slices", models.JSONField(blank=True, default=list, verbose_name="切片 (RAG)")),
                ("frames", models.JSONField(blank=True, default=list, verbose_name="关键帧 (RAG)")),
                ("captions", models.JSONField(blank=True, default=list, verbose_name="提词 (RAG)")),
                ("highlights", models.JSONField(blank=True, default=list, verbose_name="高光 (RAG)")),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_jobs",
                        to="media_assets.media",
                        verbose_name="关联媒体文件",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="workflow.annotationproject",
                        verbose_name="所属标注项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "标注任务",
                "verbose_name_plural": "标注任务",
                "ordering": ["media__sequence_number", "id"],
            },
        ),
    ]
