# Generated by Django 4.2.23 on 2025-12-23 10:48

import uuid

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_assets", "0005_asset_content_genre_asset_known_characters_and_more"),
        ("workflow", "0002_annotationjob_annotation_file_backup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneAnnotationProject",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="项目描述")),
                ("status", django_fsm.FSMField(default="PENDING", max_length=50, verbose_name="项目状态")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_annotation_projects",
                        to="media_assets.asset",
                        verbose_name="关联资产",
                    ),
                ),
            ],
            options={
                "verbose_name": "场景标注项目",
                "verbose_name_plural": "场景标注项目",
            },
        ),
        migrations.CreateModel(
            name="SceneAnnotationJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("QUEUED", "排队中"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("REVISING", "修订中"),
                            ("ERROR", "错误"),
                            ("QA_PENDING", "待审核"),
                        ],
                        default="PENDING",
                        max_length=50,
                        protected=True,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "cloud_task_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name="云端任务ID"),
                ),
                ("result", models.JSONField(blank=True, null=True, verbose_name="结果数据")),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_annotation_jobs",
                        to="media_assets.media",
                        verbose_name="关联媒体文件",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_annotation_jobs",
                        to="workflow.sceneannotationproject",
                        verbose_name="所属场景项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "场景标注任务日志",
                "verbose_name_plural": "场景标注任务日志",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="CharacterAnnotationProject",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="项目描述")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "待处理"), ("PROCESSING", "处理中"), ("COMPLETED", "已完成"), ("FAILED", "失败")],
                        default="PENDING",
                        max_length=20,
                        verbose_name="项目状态",
                    ),
                ),
                (
                    "override_characters",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON 格式的角色名称列表。若为空，则默认使用关联 Asset 的 known_characters。",
                        verbose_name="覆盖角色列表",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_projects",
                        to="media_assets.asset",
                        verbose_name="关联资产",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色标注项目",
                "verbose_name_plural": "角色标注项目",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="CharacterAnnotationJob",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("QUEUED", "排队中"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("REVISING", "修订中"),
                            ("ERROR", "错误"),
                            ("QA_PENDING", "待审核"),
                        ],
                        default="PENDING",
                        max_length=50,
                        protected=True,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cloud_task_id", models.CharField(blank=True, max_length=255, null=True, verbose_name="云端任务 ID")),
                (
                    "output_ass_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="character_annotation/outputs/%Y/%m/%d/",
                        verbose_name="生成的 ASS 字幕文件",
                    ),
                ),
                ("character_stats", models.JSONField(blank=True, default=dict, null=True, verbose_name="角色统计信息")),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_jobs",
                        to="media_assets.media",
                        verbose_name="关联媒体",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="workflow.characterannotationproject",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色标注任务",
                "verbose_name_plural": "角色标注任务",
                "ordering": ["media__sequence_number"],
            },
        ),
    ]
