# Generated by Django 4.2.23 on 2025-12-22 23:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0003_characterannotationproject_characterannotationjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterannotationjob",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
