# Generated by Django 4.2.23 on 2025-12-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0003_sceneannotationproject_sceneannotationjob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneannotationjob",
            name="error_message",
            field=models.TextField(blank=True, null=True, verbose_name="错误日志"),
        ),
    ]
