# Generated by Django 4.2.23 on 2025-12-23 03:50

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0004_alter_characterannotationjob_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneAnnotationProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("asset_id", models.UUIDField(db_index=True, verbose_name="Asset ID")),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="Project Title")),
            ],
            options={
                "verbose_name": "Scene Annotation Project",
                "verbose_name_plural": "Scene Annotation Projects",
            },
        ),
        migrations.CreateModel(
            name="SceneAnnotationJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("media_id", models.UUIDField(db_index=True, verbose_name="Media ID")),
                ("cloud_task_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing (Slicing/Uploading)"),
                            ("CLOUD_SUBMITTED", "Submitted to Cloud"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True, verbose_name="Result Data")),
                ("error_message", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="workflow.sceneannotationproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scene Annotation Job",
                "ordering": ["-created"],
            },
        ),
    ]
