# Generated by Django 4.2.23 on 2025-12-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0004_sceneannotationjob_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationproject",
            name="orchestration_graph",
            field=models.JSONField(
                blank=True, help_text="存储用户在编排工作台保存的逻辑结构数据。", null=True, verbose_name="编排图谱 (Orchestration Graph)"
            ),
        ),
    ]
