# Generated by Django 4.2.23 on 2026-01-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0005_annotationproject_orchestration_graph"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotationjob",
            name="annotation_file",
        ),
        migrations.RemoveField(
            model_name="annotationjob",
            name="annotation_file_backup",
        ),
        migrations.AddField(
            model_name="annotationjob",
            name="data",
            field=models.JSONField(blank=True, default=dict, help_text="当前工作区的全量标注数据", verbose_name="标注数据 (Current)"),
        ),
        migrations.AddField(
            model_name="annotationjob",
            name="data_backup",
            field=models.JSONField(blank=True, default=dict, help_text="上一次保存或修订前的快照", verbose_name="标注数据 (Backup)"),
        ),
    ]
