# Generated by Django 4.2.23 on 2026-01-06 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0007_remove_integrationsettings_label_studio_access_token"),
        ("workflow", "0006_remove_annotationjob_annotation_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcodingproject",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="transcodingproject",
            name="encoding_profile",
        ),
        migrations.AlterField(
            model_name="annotationproject",
            name="source_encoding_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="选择一个编码配置。标注工具将使用此配置转码后的视频，以加快加载速度。",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="configuration.encodingprofile",
                verbose_name="源编码配置",
            ),
        ),
        migrations.DeleteModel(
            name="TranscodingJob",
        ),
        migrations.DeleteModel(
            name="TranscodingProject",
        ),
    ]
