# Generated by Django 4.2.23 on 2026-01-11 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0007_remove_transcodingproject_asset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characterannotationproject",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="sceneannotationjob",
            name="media",
        ),
        migrations.RemoveField(
            model_name="sceneannotationjob",
            name="project",
        ),
        migrations.RemoveField(
            model_name="sceneannotationproject",
            name="asset",
        ),
        migrations.DeleteModel(
            name="CharacterAnnotationJob",
        ),
        migrations.DeleteModel(
            name="CharacterAnnotationProject",
        ),
        migrations.DeleteModel(
            name="SceneAnnotationJob",
        ),
        migrations.DeleteModel(
            name="SceneAnnotationProject",
        ),
    ]
